<?php

/*
 * implements hook_form_FORM_ID_alter
 * adds a section to the user profile form for the user to choose who can control this account.
 * overrides the section created by masquerade_form_user_profile_form_alter
 */
function masquerade_nominate_form_user_profile_form_alter(&$form, $form_state) {
  if ($form['#user']->uid > 1) {
    $uids = db_query('SELECT uid_from FROM {masquerade_users} WHERE uid_to = :uid', array(':uid' => $form['#user']->uid))->fetchCol();
    $accounts = user_load_multiple($uids);
    $masquerade_controllers = array();
    foreach ($accounts as $uid => $account) {
      $masquerade_controllers[] = $account->name;
    }
    //this overwrites what the masquerade module provides
    $form['masquerade'] = array(
      '#type' => 'fieldset',
      '#title' => t('Account controller(s)'),
      '#description' => t('Nominate users who can control this account.'),
      'masquerade_controllers' => array(
        '#title' => t('New controller'),
        '#type' => 'textfield',
        '#autocomplete_path' => 'masquerade/autocomplete-user',
        '#default_value' => drupal_implode_tags($masquerade_controllers),
      )
    );
  }
}


/**
 * Implements hook_user_update().
 * writes the masquerade relationships determined in the above form.
 * Mostly copied from masquerade_user_update with the to's and from's mixed up
 */
function masquerade_nominate_user_update(&$edit, $account, $category) {
  global $_masquerade_old_session_id;
  if ($category == 'account' && isset($edit['masquerade_controllers'])) {
    $query = db_delete('masquerade_users');
    $query->condition('uid_to', $account->uid);
    $query->execute();
    // Save users from settings form.
    $users = drupal_explode_tags($edit['masquerade_controllers']);
    $query = db_insert('masquerade_users')->fields(array('uid_from', 'uid_to'));
    foreach ($users as $username) {
      if ($to_user = _masquerade_user_load($username)) {
        $query->values(array(
          'uid_to' => $account->uid,
          'uid_from' => $to_user->uid,
        ));
      }
    }
    $query->execute();
    $edit['masquerade_controllers'] = NULL;

    // Update user session...
    // @TODO check other way of session API.
    if (!empty($_masquerade_old_session_id)) {
      $query = db_update('masquerade');
      $query->fields(array(
        'sid' => session_id(),
      ));
      $query->condition('sid', $_masquerade_old_session_id);
      $query->execute();
    }
  }
}

/*
 * implements hook_block_info
 */
function masquerade_nominate_block_info() {
  $blocks = array();
  $blocks['masquerade_nominate'] = array(
    'info' => t('Use another account'),
    'cache' => DRUPAL_NO_CACHE,
    //this block should not be accessible to user 1, who should instead use the block provided by maquerade, or even the devel-switch_users block
  );
  return $blocks;
}

/*
 * implements hook_block_view
 * This block is similar the masquerade block, but with out the search field.
 */
function masquerade_nominate_block_view($delta) {
  $real_uid = @$_SESSION['masquerading'] ?  $_SESSION['masquerading'] : $GLOBALS['user']->uid;
  $switch_to_uids = db_query("SELECT uid_to FROM {masquerade_users} WHERE uid_from = :uid_from", array(':uid_from' => $real_uid))->fetchCol();
  foreach ($switch_to_uids as $uid) {
    if ($uid != $GLOBALS['user']->uid) {
      $account = user_load($uid);
      $switch_link = 'masquerade/switch/' . $account->uid;
      $switch_links[] = l($account->name, $switch_link, array('query' => array('token' => drupal_get_token($switch_link))));
    }
  }
  if (@$_SESSION['masquerading']) {
    $switch_links[] = l(t('Switch back'), 'masquerade/unswitch', array('query' => array('token' => drupal_get_token('masquerade/unswitch'))));
  }
  if (empty($switch_links)) return;
  return array(
    'subject' => t('Control account'),
    'content' => theme('item_list', array('items' => $switch_links))
  );
}

